package:
  name: c3dp
  version: v0.1.0

source:
  git_rev: v0.1.0
  git_url: https://github.com/Fahima-Islam/c3dp.git

requirements:
  build:
    - python
    - numpy
    - scipy
    - matplotlib
    - lmfit
    - pytest
    - pytest-runner

  run:
    - python
    - numpy
    - scipy
    - matplotlib
    - lmfit
    - pytest
    - pytest-runner
    - mcvine-core
    - mantid-framework

test:
  imports:
    - c3dp
  
about:
  home: 
# http://c3dp.readthedocs.io/en/latest/
  license:
  license_file:
