package:
  name: chop
  version: v0.1.0

source:
  git_rev: v0.1.0
  git_url: https://github.com/ornlneutronimaging/chop.git

requirements:
  build:
    - python
    - numpy
    - scipy
    - matplotlib
    - pytest
    - pytest-runner

  run:
    - python
    - numpy
    - scipy
    - matplotlib
    - pytest
    - pytest-runner

test:
  imports:
    - chop
  
about:
  home: 
# http://chop.readthedocs.io/en/latest/
  license:
  license_file:
